#!/bin/sh

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -eq 0 ]
then
    printf 'Usage: %s COMMAND [ARG...]\n' "${0##*/}" >&2
    exit 1
fi

if ! command -v pipetty > /dev/null
then
    printf '%s requires pipetty <https://github.com/kilobyte/colorized-logs>\n' "${0##*/}" >&2
    exit 1
fi
if [ -n "${PAGER-}" ]
then
    pager="$PAGER"
elif command -v pager > /dev/null
then
    pager='pager'
else
    pager='more'
fi
export LESS="R${LESS-}"
export LV="-c ${LV-}"
export PAGER='cat'
size=$(TERM=${TERM:-dumb} tput -S <<EOF
cols
lines
EOF
)
# shellcheck disable=SC2183,SC2086
size=$(printf '%d %d' $size)
read -r cols lines <<EOF
$size
EOF
exec pipetty sh -c "stty cols $cols rows $lines <&1; "'exec "$@"' pagerboy-wrapper "$@" | "$pager"

# vim:ts=4 sts=4 sw=4 et
