name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: run shellcheck
      run:
        shellcheck pagerboy
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install deps
      run:
        sudo apt-get install colorized-logs
    - name: smoke test
      run:
        PAGER=hd ./pagerboy echo moo

# vim:ts=2 sts=2 sw=2 et
